#version 450

layout(local_size_x = 32, local_size_y = 32) in;

layout(binding = 0) uniform UniformBufferObject {
    float time;
} ubo;

layout(binding = 1, rgba8) uniform image2D img; 

void main() {
    const float pi = 3.1412;
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    float sz = (0.5 * sin(((coords.x)/ 1024.0) * pi * 4 + ubo.time)) + 0.5;
    vec4 color = sz * vec4(0.4, 0.3, 0.9, 1.0);
    imageStore(img, coords, color);
}